on:
  push:
  pull_request:

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_command: python -c 'import auto_publish_test'
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
